version: 2

sources:
    - name: dezdb
      schema: dezdb
      tables:
        - name: stg_games_aggregated
        - name: stg_games_detailed
        - name: stg_games_reviews

models:
    - name: reviews
      description: >
        19M reviews of boardames on BoardGameGeek up to 2022-01-08
      columns:
          - name: user
            description: An author of the comment
          - name: rating 
            description: Average rating of the game, from 0.0 to 10.0
          - name: comment 
            description: Comment on the website
          - name: id 
            description: Game id as used by bgg.com
          - name: name 
            description: Game name
          - name: comment_len_bucket
            description: Comment category based on length, bucket's range described in column's value

    - name: detailed
      description: >
        Rich information about boardgames
      columns:
          - name: type
            description: Always a boardgame
          - name: id
            description: Game's ID
          - name: thumbnail
            description: Link to the preview image of the game
          - name: image
            description: Link to the image of the game
          - name: primary
            description: Primary name of the game, usually in english
          - name: alternate
            description: Other names for the game, mainly different languages
          - name: description
            description: Text description of the game
          - name: yearpublished
            description: The year the game was published
          - name: minplayers
            description:  Minimum amount of players the game is playable with
          - name: maxplayers
            description: Maximum amount of players the game is playable with
          - name: suggested_num_players
            description: The suggestions that users have given for the optimal number of players
          - name: suggested_playerage
            description: The suggestions that users have given for how old someone needs to be to play
          - name: suggested_language_dependence
            description: The suggestions that users have given for easy the game is to play in different languages
          - name: playingtime
            description: The suggestions that users have given for how long does it take to play
          - name: minplaytime
            description: Minimal game time in minutes
          - name: maxplaytime
            description: Maximum game time in minutes
          - name: minage
            description: Minimum age required to play
          - name: boardgamecategory
            description: Details the category of the game
          - name: boardgamemechanic
            description: Details the mechanics the game uses, such as bluffing
          - name: boardgamefamily
            description: ""
          - name: boardgameexpansion
            description: "" 
          - name: boardgameimplementation
            description: "" 
          - name: boardgamedesigner
            description: "" 
          - name: boardgameartist
            description: "" 
          - name: boardgamepublisher
            description: "" 
          - name: usersrated
            description: "" 
          - name: average
            description: "" 
          - name: bayesaverage
            description: "" 
          - name: board_game_rank
            description: "" 
          - name: strategy_game_rank
            description: "" 
          - name: family_game_rank
            description: "" 
          - name: stddev
            description: "" 
          - name: median
            description: "" 
          - name: owned
            description: "" 
          - name: trading
            description: "" 
          - name: wanting
            description: "" 
          - name: wishing
            description: "" 
          - name: numcomments
            description: "" 
          - name: numweights
            description: "" 
          - name: averageweight
            description: "" 
          - name: boardgameintegration
            description: "" 
          - name: boardgamecompilation
            description: "" 
          - name: party_game_rank
            description: "" 
          - name: abstract_game_rank
            description: "" 
          - name: thematic_rank
            description: "" 
          - name: war_game_rank
            description: "" 
          - name: customizable_rank
            description: "" 
          - name: childrens_game_rank
            description: "" 
          - name: rpg_item_rank
            description: "" 
          - name: accessory_rank
            description: "" 
          - name: video_game_rank
            description: "" 
          - name: amiga_rank
            description: "" 
          - name: commodore_64_rank
            description: "" 
          - name: arcade_rank
            description: "" 
          - name: atari_st_rank
            description: "" 